### PR TITLE
Fix badge URL in README

### PR DESCRIPTION
**Pull request by purcell**

### CODE REVIEW

**Comment by purcell** [comment]
Struggling to see why it's helpful to have the pedantic commit / PR message checking in this very low-traffic repo. This PR was a simple doc fix via the GitHub editor.

- It's not necessary to discourage casual contributors by making them re-work their PRs to fit title style guides
- Since adding this checker, the only effect has been NO-ISSUE cruft in all commits

**Comment by remi-gelinas** [comment]
Mostly it was to ensure commits adhered to conventional spec, so automatic versioning and releases could be done. That being said, at this point I agree - it would be far simpler to manually tag for release I think, and workflow off of that. Once I've been added as the team owner for this repo again I will rework the release flow to make contribution easier.

**Comment by purcell** [comment]
Makes sense. Perhaps @adisbladis (as local Emacs + Nix head honcho) would be able to make you a team owner?

**Comment by remi-gelinas** [comment]
Yep, I've just pinged him in the original repo transfer thread again to get some eyes on it!

**Comment by remi-gelinas** [comment]
@purcell Realized I totally blanked and included this in #23 - sorry about that. I'll close this out as it's done!

**Comment by purcell** [comment]
Haha, no worries — thanks!

**Pull request closed without merging**
