### PR TITLE
Improve indent rules

### LINKED ISSUE #27: support indenting attrset args according to RFC 166
Trying to indent the args here does not work; it forces them onto column 0:

```
{
config,
pkgs,
lib,
...
}:
```

Perhaps the rule of "one further than the parent" could be generalised now that we have an official Nix style which lays out precise rules on that: https://github.com/NixOS/rfcs/pull/166

### PR DESCRIPTION
**Pull request by heraplem**
This fixes #27 and #45.

### CODE REVIEW

**Review by purcell — APPROVED** [review]

**Comment by purcell** [comment]
Approved in principle. Some tests are failing, so I won't merge right away. :)

**Comment by antifuchs** [comment]
This looks super promising! Do you see why indent-formals is failing on 29.1 there?

**Comment by heraplem** [comment]
Should be fixed now.

**Review by purcell — APPROVED** [review]

**Comment by purcell** [comment]
Thanks!

**Pull request merged**
